### PR TITLE
Added support to dynamically generate the schema.json.

### LINKED ISSUE #5: Automatically run introspection query and build schema.json
I wonder if it would be possible to automatically run the introspection query against a given graphql endpoint prior to building the java apollo client. I believe the apollo cli can download the schema with something like `apollo schema:download OUTPUT`.

Is there anything limiting the ability to do this? Re-downloading the results of an introspection query and checking it in frequently as a manual process would be a nice workflow to automate.

### PR DESCRIPTION
**Pull request by kodayashi**
Schema can be generated dynamically at build time with these new options:

    <generateIntrospectionFile>false</generateIntrospectionFile>
    <schemaUrl>http://localhost</schemaUrl>

Closes #5

### CODE REVIEW

**Comment by kodayashi** [comment]
@Sparow199 - I can't seem to pull this version of the plugin down. Has it been built and deployed?

`Failure to find com.github.sparow199:apollo-client-maven-plugin:jar:1.3.1`

**Comment by Sparow199** [comment]
I'm sorry, I haven't synchronized with maven central. I'll fix it asap

**Comment by kodayashi** [comment]
Thanks @Sparow199 - I'll try it again in a few hours.

**Comment by Sparow199** [comment]
@kodayashi the syncronisation between Jcenter and [Maven central](https://search.maven.org/artifact/com.github.sparow199/apollo-client-maven-plugin-parent/1.3.1/pom) is done.

**Pull request merged**
